services:
  app:
    environment:
      OTEL_SERVICE_NAME: document-lab
      DEPLOYMENT_ENVIRONMENT: lab
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://otlp-gateway-prod-gb-south-1.grafana.net/otlp/v1/traces
      GRAFANA_CLOUD_STACK_ID: "1820535"
      GRAFANA_CLOUD_TOKEN_FILE: /run/secrets/grafana_cloud_token
    secrets:
      - grafana_cloud_token
secrets:
  grafana_cloud_token:
    file: .local/cloud-token
